name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 1.0.1
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
