name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 2.0.3
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  test: ^1.25.0
  very_good_analysis: ^5.1.0

