name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 2.3.1
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

