name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 1.0.0
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: '>=2.19.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
