name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 2.3.8
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.15.0
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0

