name: i3_ipc
description: An I3 ipc client library written in Dart.
version: 2.0.7
repository: https://github.com/AR-CADE/i3_ipc

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  rxdart: ^0.27.7
  uuid: ^4.3.3

dev_dependencies:
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

