name: Dart CI

on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: dart pub get
      -  run: dart fix --apply
      -  run: dart format --set-exit-if-changed .
  
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: dart pub get
      -  run: dart analyze

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: dart pub get
      -  run: dart test

  build_bin:
    name: Build Example exe artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart pub get
      - run: dart compile exe bin/i3_ipc_example.dart
      - uses: actions/upload-artifact@v3
        with:
          name: example-linux
          path: bin/i3_ipc_example.exe
  